language: objective-c
osx_image: xcode9.2
branches:
  only:
    - master
before_install:
  - brew install carthage
script:
  - carthage bootstrap
  - xcodebuild -scheme "EllipticCurveTests" -destination "platform=iOS Simulator,name=iPhone 5s" test
